@startuml

!define PUMLLibrary https://raw.githubusercontent.com/avensolutions/plantuml-cloud-image-library/main
!includeurl PUMLLibrary/general/general.puml

skinparam rectangle<<boundary>> {
    Shadowing false
    StereotypeFontSize 0
    FontColor #444444
    BorderColor #444444
    BorderStyle dashed
}

rectangle "AWS" <<boundary>> {
    $Documents(documents, Documents, Documents)
    $User(user, User, User)
    $Users(users, Users, Users)
    $Email(email, Email, Email)
}

@enduml