@startuml

!define Library https://raw.githubusercontent.com/infraql/plantuml-cloud-resource-library/main
!includeurl Library/aws/aws.puml

skinparam rectangle {
    StereotypeFontSize 12
    shadowing false
}

skinparam rectangle<<boundary>> {
    Shadowing false
    StereotypeFontSize 0
    FontColor #444444
    BorderColor #444444
    BorderStyle dashed
}

rectangle "AWS" <<boundary>> {
    $AwsTransferFamily(sftpgw, SFTP/FTPS Gateway, AWS Transfer Family)
    $AwsS3(s3landing, Landing Bucket, AWS S3 Bucket)
    $AwsLambda(lambda, S3 Object Notification, AWS Lambda Function)
    $AwsGlue(gluejobs, Glue ETL Jobs, AWS Glue)
    $AwsGlue(gluecatalog, Glue Catalog, AWS Glue)
    $AwsS3(s3staging, Staging Bucket, AWS S3 Bucket)
    $AwsSns(sns, SMS/Email/Push Notifications, AWS SNS)
}

@enduml