@startuml

!$githubroot = "https://github.com/avensolutions/plantuml-cloud-image-library/raw/main"
skinparam defaultTextAlignment center

'
' GitLab PlantUML Resource Library
'

!$imagesroot = %string($githubroot + "/gitlab")

!unquoted procedure $GitLab($alias, $label, $techn, $descr="", $stereo="GitLab")
    rectangle "==$label\n\n<img:$imagesroot/images/gitlab.png>\n//<size:12>[$techn]</size>//" <<$stereo>> as $alias #white
!endprocedure

@enduml