@startuml

'
' General PlantUML Resource Library
'

skinparam defaultTextAlignment center

!$urlroot = "https://github.com/infraql/plantuml-cloud-resource-library/raw/main/general/images"

!unquoted procedure $User($alias, $label, $techn, $descr="", $stereo="User")
    rectangle "==$label\n\n<img:$urlroot/Res_User_48_Light.png>\n//<size:12>[$techn]</size>//" <<$stereo>> as $alias #white
!endprocedure

@enduml